server:
  port: 8080

spring.jpa.properties.hibernate.enable_lazy_load_no_trans: true

rest.security.issuer-uri: http://remy-trompier.ch:9000/auth/realms/test
#rest.security.issuer-uri: http://vmld-00022.hcuge.ch:8088/auth/realms/hug

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${rest.security.issuer-uri}

log.level: INFO

logging:
  level:
    ROOT: ${log.level}
    org.springframework.security: ${log.level}
    com.example.demo.config: ${log.level}
    org.springframework.web.filter.CommonsRequestLoggingFilter: ${log.level}
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    reactor.ipc.netty.channel.ChannelOperationsHandler: ${log.level}
    reactor.ipc.netty.http.server.HttpServer: ${log.level}
    reactor.ipc.netty.http.client: ${log.level}
    io.reactivex.netty.protocol.http.client: ${log.level}
    io.netty.handler: ${log.level}
    io.netty.handler.proxy.HttpProxyHandler: ${log.level}
    io.netty.handler.proxy.ProxyHandler: ${log.level}
    org.springframework.web.reactive.function.client: ${log.level}
    reactor.ipc.netty.channel: ${log.level}

spring.http.log-request-details: true  

